esphome:
  name: alpha2go
  friendly_name: "Grundfos Alpha2 Go"


esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    #sdkconfig_options: 
      # Improve WiFi/BLE coexistence on single-radio ESP32-C3
      #CONFIG_ESP_COEX_SW_COEXIST_ENABLE: "y"
      #CONFIG_ESP_WIFI_SW_COEXIST_ENABLE: "y"
      # Disable WPA3 - fixes auth issues with UniFi APs
      #CONFIG_ESP_WIFI_ENABLE_WPA3_SAE: "n"
      #CONFIG_ESP_WIFI_ENABLE_SAE_PK: "n"

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # WiFi optimization for hardware interference
  power_save_mode: none          # Disable power saving for better stability
  output_power: 8.5              # Reduce TX power (default 20dB) - try 15dB or 12dB if issues persist
  fast_connect: true             # Skip scanning, connect faster (requires static IP)
  # enable_btm: false              # Disable BSS Transition Management
  # enable_rrm: false              # Disable Radio Resource Management

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Alpha2Go_Fallback_Hotspot"
    password: !secret fallback_hotspot_password
  
  #manual_ip: 
  #  static_ip: xxx.xxx.xxx.xxx
  #  gateway: xxx.xxx.xxx.xxx
  #  subnet: 255.255.255.0
    
captive_portal:

# Web interface for local access
web_server:
  port: 80

# Load the alpha2 component from local components folder
external_components:
  - source: 
      type: local
      path: "esphome-alpha2go/components"

# BLE tracker - tuned for WiFi coexistence on single-radio ESP32-C3
esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    active: false
    interval: 1200ms   # scan every 1.2s (default 320ms) - gives WiFi much more airtime
    window: 30ms       # short scan window to minimize radio contention

# BLE client connection to the pump
ble_client:
  - mac_address: XX:XX:XX:XX:XX:XX  # Replace with your pump's Bluetooth MAC address
    id: heatingpump

# Status LED on GPIO8 - shows WiFi connection state
# Solid = connected, Blinking = connecting/no WiFi
status_led:
  pin:
    number: GPIO8

# Alpha2 sensor platform
sensor:
  - platform: alpha2
    ble_client_id: heatingpump
    flow:
      name: "Pump Flow"
    head:
      name: "Pump Head Pressure"
    speed:
      name: "Pump Speed"
    power:
      name: "Pump Power"
    voltage:
      name: "Pump Voltage"
    current:
      name: "Pump Current"
